services:
  frontend:
    image: kdarley/fireequipmentfrontend:latest
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: production
    expose:
      - "3000"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      certbot certonly --webroot -w /var/www/certbot
      --email you@example.com --agree-tos --no-eff-email
      -d yourdomain.com || true;
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h & wait $${!};
      done;'

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
