version: "3.9"

services:
  frontend:
    image: kdarley/fireequipmentfrontend:latest
    container_name: frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      POSTGRES_URL: ${POSTGRES_URL}   # Injected from host / GitHub Actions
      NEXTAUTH_URL: https://darleyx.com
      TRUSTED_HOSTS: https://darleyx.com
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /docker-data/certbot/conf:/etc/letsencrypt:ro
      - /docker-data/certbot/www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - /docker-data/certbot/conf:/etc/letsencrypt
      - /docker-data/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot --quiet;
        sleep 12h & wait $${!};
      done;'
