name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: kdarley/fireequipmentfrontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted    # your EC2 runner label(s)

    steps:
      - name: Pull latest Docker image
        run: docker pull kdarley/fireequipmentfrontend:latest

      - name: Stop existing container (if running)
        run: |
          if [ "$(docker ps -q -f name=fireequipmentfrontend)" ]; then
            docker stop fireequipmentfrontend
            docker rm fireequipmentfrontend
          fi

      - name: Start container with new image
        run: |
          docker run -d --name fireequipmentfrontend -p 3000:3000 kdarley/fireequipmentfrontend:latest
