name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: kdarley/fireequipmentfrontend:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout repo on runner
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clean up Docker to free space
        run: docker system prune -af --volumes || true

      - name: Pull latest Docker images
        run: |
          docker pull kdarley/fireequipmentfrontend:latest
          docker pull nginx:latest
          docker pull certbot/certbot:latest

      - name: Stop and remove existing containers
        run: docker compose down || echo "No containers to stop"

      - name: Start containers
        run: docker compose up -d
