name: Build, Push, and Deploy

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: kdarley/fireequipmentfrontend:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted   # Your EC2 runner

    env:
      POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
      # NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      # NEXTAUTH_URL: https://darleyx.com
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_URL: https://darleyx.com
      DOMAIN: ${{ secrets.PROD_DOMAIN }}
      LE_EMAIL: ${{ secrets.LE_EMAIL }}
      LETSENCRYPT_STAGING: ${{ vars.LETSENCRYPT_STAGING || 'false' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify Docker and Compose
        run: |
          docker --version
          docker compose version

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Ensure persistent directories exist
        run: |
          mkdir -p /docker-data/certbot/conf /docker-data/certbot/www
          sudo chown -R $USER:$USER /docker-data

      - name: Pull images
        run: |
          docker pull ${{ env.IMAGE_NAME }}
          docker pull nginx:latest
          docker pull certbot/certbot:latest

      - name: Render Nginx templates
        run: |
          mkdir -p nginx/conf.d
          sed "s/{{DOMAIN}}/${DOMAIN}/g" nginx/templates/bootstrap.conf.template > nginx/conf.d/site.conf.bootstrap
          sed "s/{{DOMAIN}}/${DOMAIN}/g" nginx/templates/app.conf.template > nginx/conf.d/site.conf.app

      - name: Bootstrap cert if missing
        run: |
          set -e
          CERT_DIR="/docker-data/certbot/conf/live/${DOMAIN}"
          STAGING_FLAG=""
          if [ "${LETSENCRYPT_STAGING}" = "true" ]; then
            STAGING_FLAG="--staging"
          fi

          if [ ! -d "$CERT_DIR" ]; then
            echo "No certs found. Bootstrapping..."
            cp nginx/conf.d/site.conf.bootstrap nginx/conf.d/site.conf
            docker compose up -d nginx
            sleep 5
            docker compose run --rm certbot certonly --webroot -w /var/www/certbot \
              --email "${LE_EMAIL}" --agree-tos --no-eff-email ${STAGING_FLAG} \
              -d "${DOMAIN}" -d "www.${DOMAIN}"
            docker compose down
            cp -f nginx/conf.d/site.conf.app nginx/conf.d/site.conf
          else
            echo "Existing certs found for ${DOMAIN}."
            cp -f nginx/conf.d/site.conf.app nginx/conf.d/site.conf
          fi

      - name: Clean Docker environment before deploy
        run: |
          docker stop $(docker ps -q) || true
          docker rm $(docker ps -aq) || true
          docker image prune -af
          docker volume prune -f
          docker network prune -f

      - name: Deploy stack
        run: docker compose up -d --force-recreate
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

      - name: Show running containers
        run: docker ps --format "table {{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"

      - name: Tail Nginx logs (last 100 lines)
        if: always()
        run: docker logs --tail 100 nginx || true
